### PR TITLE
Add an option to submit form immediately when recognition ends

### PR DESCRIPTION
**Pull request by ob-ivan**
Use data-instant-submit to achieve that

### CODE REVIEW

**Comment by ob-ivan** [comment]
We should also check whether there was any input, to avoid empty form submits. I just don't see how to do that yet.

**Comment by ob-ivan** [comment]
Also, not really sure what happens if there is no form element in the element's ancestor chain. 'ancestor.something is undefined' exception is the most likely scenario.

**Comment by ob-ivan** [comment]
Tested the no-form case. document.parentNode is null, the for loop exits normally.

**Comment by Daniel-Hug** [comment]
Thanks, sounds like a good feature to me. I merged this with changes.

**Comment by ob-ivan** [comment]
We now have a little unexpected side-effect: if I input something from the keyboard, and then I click the mic button, and Chrome blocks the page from using the mic (because of HTTP), the `recognition.onend` callback gets called immediately (surprise!), and submit occurs (with data-instant-submit set to true).

I think I'll come up with a fix shortly, along with a new option I intended to add anyway -- clearing the input when the button is clicked.

**Comment by ob-ivan** [comment]
> I think I'll come up with a fix shortly

No luck, I created #9 instead to handle that.

**Pull request merged**
